#!/bin/bash

if [ "$1" == "backup" ]
then
	if ! [[ -e ~/.local/share/snippet-box ]]
	then
		echo "No data found."
		exit 1
	fi

	cp ~/.local/share/snippet-box/db.sqlite3 .
	tar -czvf snippets_data.tar.gz db.sqlite3
	rm db.sqlite3

	exit 0
fi

if ! [[ -e ~/bin/snippet-box ]]
then
	docker rmi snippet-box
	git clone https://github.com/pawelmalak/snippet-box ~/bin/snippet-box
	cd ~/bin/snippet-box
	docker build -t snippet-box .
fi

if which docker > /dev/null 2>&1
then
	docker run --rm -p 5000:5000 -v ~/.local/share/snippet-box:/app/data snippet-box
else
	echo "Docker is not installed."
fi
