- name: "Install fish configuration files"
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    user_home: "{{ lookup('env', 'HOME') | default(lookup('env', 'USERPROFILE')) }}"
    config_folder: "{{ playbook_dir }}/../config/"
  tasks:
    - debug: var=user_home

    - name: "Create parent .config folder"
      ansible.builtin.shell:
        cmd: "mkdir -p {{user_home}}/.config/fish"
      register: aptout
    - debug: var=aptout

    - name: "Move to ~/.config/"
      ansible.builtin.shell:
        cmd: "cp {{config_folder}}/fish/config.fish {{user_home}}/.config/fish/"
      register: aptout2
    - debug: var=aptout2
